dist: xenial
language: node_js
os: windows
node_js: 10
matrix:
  allow_failures:
    - os: windows
addons:
  chrome: stable
install: if [[ -z "$TRAVIS_TAG" ]]; then npm install; fi
script: if [[ -z "$TRAVIS_TAG" && "$TRAVIS_OS_NAME" != "windows" ]]; then NODE_ENV=test
  npm test; fi
dist: xenial
language: node_js
cache:
  - directories:
      - node_modules
      - frontend/node_modules
matrix:
  fast_finish: true
  allow_failures:
    - os: windows
addons:
  chrome: stable
install: if [[ -z "$TRAVIS_TAG" ]]; then npm install; fi
script: if [[ -z "$TRAVIS_TAG" && "$TRAVIS_OS_NAME" != "windows" ]]; then NODE_ENV=test
  npm test; fi

notifications:
  email: false
  
